Migrated to nndb.
Komposten/public_suffix pull request #7
Opened 2021-03-19 01:24 UTC by bsutton

Breaking Changes: The factory constructors PublicSuffix.fromString and PublicSuffix.fromurl hand to be changed to static methods and nndb does not allow a factory to return a null object. This should have minimal impact on existing code ahs the call convention is identical.

2021-03-19 01:24 UTC, bsutton commented
I hope you can accept and publish this to pub.dev as I have a project that is reliant on public_suffix.

2021-03-19 09:01 UTC, Komposten commented
Ah, I didn't know they'd been working on NNDB in Dart! 😮 

I'm busy this weekend but can hopefully take a look at this in the beginning of next week.

2021-03-19 09:39 UTC, Komposten commented
One note in the meantime: please follow the repo's [commit message conventions](https://github.com/Komposten/public_suffix#contributing) 🙂

2021-03-27 13:15 UTC, Komposten requested changes
Mostly looks good, but I've got a few remarks (see requested changes).

Also, just to re-iterate, please update the commit messages to follow the [contribution guidelines](https://github.com/bsutton/public_suffix#contributing).

2021-03-27 13:15 UTC, Komposten commented on lib/src/default_suffix_rules.dart
> +  static SuffixRules? rulesOrThrow() {
Should not have a nullable result here since the method throws if `_rules == null`.

2021-03-27 13:15 UTC, Komposten commented on example/static_list.dart
> +  var parsedUrl = PublicSuffix.fromString('https://www.komposten.github.io')!;
We should probably just use the normal constructor here for implicit null-safety.

2021-03-27 13:15 UTC, Komposten commented on example/static_list.dart
> +  parsedUrl = PublicSuffix.fromString('https://www.xn--6qq79v.cn')!;
Same as previous, use the normal constructor.

2021-03-27 13:15 UTC, Komposten commented on example/instance_list.dart
> +      suffixRules: suffixRules)!;
We should probably just use the normal constructor here for implicit null-safety.

2021-03-27 13:15 UTC, Komposten commented on example/instance_list.dart
> +  parsedUrl = PublicSuffix.fromString('https://www.xn--6qq79v.cn')!;
Same as previous, use the normal constructor.

Also, we should be specifying `suffixRules: suffixRules` here (I appear to have missed that when I originally wrote this example...).

2021-03-27 13:15 UTC, Komposten commented on lib/src/public_suffix_base.dart
> +  PublicSuffix? _punyDecoded;
Many of the fields in this class should be non-nullable (and probably late).
- `_sourceUrl`: the constructor throws if it can't be set
- `_sourcePunycoded`: initialised with a default value of false (as you already do)
- `_hasKnownSuffix`: is given a value when parsing (that value can be passed into `PublicSuffix._` to initialise it in there as well).
- `_root`: is given a value when parsing
- `_suffix`: is given a value when parsing
- `_icannRoot`: is given a value when parsing
- `_icannSuffix`: is given a value when parsing
- `_punyDecoded`: is given a value when parsing, even if the source URL isn't punycoded (`PublicSuffix._` can simply do `_punyDecoded = this` to initialise it).

Obviously this also applies to the respective getters.

2021-03-27 13:15 UTC, Komposten commented on lib/src/utilities.dart
> +    var rules = suffixRules!.ruleMap[split.last] ?? <String>[];
Since we're editing this line we might as well replace `<String>[]` with just `[]` to avoid the cast in the for loop.
(Another little mistake I've made... 😬)

2021-03-29 21:58 UTC, bsutton commented on example/static_list.dart
> +  var parsedUrl = PublicSuffix.fromString('https://www.komposten.github.io')!;
agreed

2021-03-29 21:58 UTC, bsutton commented on lib/src/default_suffix_rules.dart
> +  static SuffixRules? rulesOrThrow() {
agreed

2021-03-29 22:20 UTC, bsutton commented on example/instance_list.dart
> +      suffixRules: suffixRules)!;
I changes this to the default constructor given it can't be null.

2021-03-30 17:13 UTC, Komposten approved these changes

2021-03-30 17:26 UTC, merged

2021-04-01 16:32 UTC, Komposten commented
@bsutton 3.0.0 is now released on pub.dev 🙂